### ISSUE TITLE
Add option to configure expiration time of cache objects

### ISSUE THREAD

**Issue by myniva** [myniva/gradle-s3-build-cache#1]
In AWS S3, customers pay per GB storage used. To keep costs low, it might be desirable to clean up cache items after a certain amount of time.

S3 has the concept of "expiration actions", see http://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html We should consider adding an `expiration` configuration key which would control the S3 lifecycle of the cache objects.

**Comment by ScottPierce** [comment]
This is now supported by the Gradle plugin https://docs.gradle.org/current/release-notes.html

```groovy
buildCache {
    local {
        // Set target size to 10GB
        targetSizeInMB = 10240
    }
}
```

Does this plugin work properly with Gradle 4.0?

**Comment by myniva** [comment]
Hi @ScottPierce I just released version 0.3.0 of the plugin which is compatible with Gradle 4.0 (see #3). The work on this ticket is ongoing. I hope I can release another version in the coming week. I'll keep you posted.

**Comment by antillean** [comment]
I think S3 expiration actions are configured per-bucket, not per-object, so it would -- and probably should -- be up to users to configure a sensible expiration policy when they set up the S3 bucket for the build cache. Maybe the project's README can suggest that people do this when setting up an S3 bucket for the build cache.

**Comment by myniva** [comment]
As @antillean has mentioned, the eviction of cache objects should be handled by using an S3 Object Lifecycle (https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html).

@erdi as you're doing some testing anyway, would it be possible to give this solution a try and - if everything works smoothly - add some instructions to the readme?
