### ISSUE TITLE
Support for other methods of providing credentials

### ISSUE THREAD

**Issue by itsnagaraj** [myniva/gradle-s3-build-cache#30]
Are there any plans to support other methods of retrieving credentials for the plugin? For instance

a) Loading a credentials file and specifying a profile. Currently the only way to support this is to `export AWS_PROFILE=<profile_name>`.

b) AWS SSO credentials. AWS CLI 2 supports SSO to retrieve short lived credentials and use a profile name to access resources. Cache plugin does not have any mechanism to support this either

Proposing additional configuration to specify credentials

**Default Chain**
```
{
    credentials: {
        strategy: default
    }
}
```

**Profile**
```
{
     credentials: {
        strategy: profile
        profile: default or <profile_name>
    }
}
```

AWS SSO does not write the credentials to ~/.aws/credentials file and instead relies on configuration specified in ~/.aws/profile file and store the creds in seperate file under ~/.aws/sso directory.

Happy to work with you on this and hear your thoughts.

**Comment by myniva** [comment]
Thanks a lot for sharing your feedback and coming up with an improvement proposal.

For authentication, the plugin uses the default credentials chain. This is how most of the tools interacting with AWS are built.
I can see, that out of the box, this approach does not support all the possible authentication variations. However, I don't think that it should be an integral part of the plugin to support all these scenarios. It is out of the scope of what this plugin is about. I can also not see how we would manage to test all this scenarios in QA.

There are other tools targeting that aspect of interacting with the AWS API. Examples are [aws-vault](https://github.com/99designs/aws-vault) or [awsume](https://github.com/trek10inc/awsume).

Should I've misunderstood your proposal or if there is any other points you would like to add to the discussion, don't hesitate to reopen this issue again.
