### ISSUE TITLE
SSE Algorithm 

### ISSUE THREAD

**Issue by cdsap** [myniva/gradle-s3-build-cache#33]
Hi, thanks for this project. 
Our infra requires encryption when we are using permissions like PutObject. 
It's possible to add more properties in the configuration to accept at least AES256?

```
meta.setSSEAlgorithm(ObjectMetadata.AES_256_SERVER_SIDE_ENCRYPTION);
```

Are the project open for PR? I can create one.

Thanks

**Comment by myniva** [comment]
Thanks for using the project!

Would enabling default encryption on your S3 bucket solve the issue? See https://docs.aws.amazon.com/AmazonS3/latest/user-guide/default-bucket-encryption.html
