### ISSUE TITLE
Treat 403 (forbidden) response like 404 (not found)

### ISSUE THREAD

**Issue by vlsi** [myniva/gradle-s3-build-cache#38]
If S3 bucket is configured in "allow only GetObject for public access", then it returns 403 in case the requested object is not found.

That is made for the security reasons so no-one can tell if the object is missing or they just don't have permissions to access it.

However, the `s3-build-cache` does not really need `listobjects` permissions to retrieve cache values, so it would be nice if the cache could treat 403 responses like `cache entry not found`.

WDYT?

**Comment by myniva** [comment]
A 403 is telling you that something with your permissions is wrong, whereas a 404 says that the (cache) object does not exists. So lets assume, the cache object exists, but you just don't have the permission to access it. In that situation, you wouldn't want the plugin to treat the 403 just the same way as if the object does not exist.
