### ISSUE TITLE
Use Kotlin DSL for build scripts and implementation?

### ISSUE THREAD

**Issue by vlsi** [myniva/gradle-s3-build-cache#42]
Kotlin adds type safety, and it is included by default in the modern Gradle distributions (I guess it is available since 4.10 or so).
Kotlin helps writing tests as it has multi-line string literals.

What do you think of using Kotlin?

**Comment by vlsi** [comment]
Just in case, I've migrated code to Kotlin and implemented #36, #37, #38, #39  in my fork:
https://github.com/myniva/gradle-s3-build-cache/compare/master...vlsi:master

**Comment by myniva** [comment]
I agree, Kotlin comes with some very nice language features.

Nevertheless, I want to stick with Java for this project. Reason is that I want the project to be "open" for as many contributors as possible. Java is still order of magnitudes more popular than Kotlin.
